server:
  port: 9999

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testdb
    username: root
    password: 1234

  thymeleaf:
    cache: false

logging:
  level:
    root: info
    wind.yang: debug

kafka:
  bootstrapAddress: localhost:9092

message:
  topic:
    name: mytopic